name: "Terraform AWS Deploy"

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Securely configure AWS credentials from GitHub Secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      # Create terraform.tfvars from workflow/environment variables
      - name: Generate terraform.tfvars from secrets
        run: |
          cat <<EOF > terraform.tfvars
          allowed_cidr = "${{ secrets.ALLOWED_CIDR }}"
          name_prefix = "gh-actions"
          # Add other non-secret variables here if needed
          EOF

      # Optionally, export TF_VAR_* secrets for use as sensitive Terraform variables
      # Example: admin_password picked up by Terraform as var.admin_password
      - name: Export TF_VAR_* secrets
        run: |
          # echo "TF_VAR_admin_password=${{ secrets.TF_VAR_ADMIN_PASSWORD }}" >> $GITHUB_ENV
          # Add more as needed

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate

      - name: Terraform apply
        run: terraform apply -auto-approve

      # Optionally, add a destroy job for teardown (manually or on schedule)
