name: "Terraform AWS Destroy"

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Generate terraform.tfvars from secrets
        run: |
          cat <<EOF > terraform.tfvars
          allowed_cidr = "${{ secrets.ALLOWED_CIDR }}"
          name_prefix = "gh-actions"
          # Add other non-secret variables if needed
          EOF

      # Export any TF_VAR_* secrets as needed

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform destroy
        run: terraform destroy -auto-approve
